title: Elite Estates
description: "Predicting house prices based on its features!"
github_repo: "teacher_portfolio"
baseurl: "/teacher_portfolio"
future: true
remote_theme: jekyll/minima
minima:
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.html


